version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
      - CORS_ORIGIN=*
      - BAIDU_API_KEY=xmEObbrYbzwfjX8Vn2ePiQXI
      - BAIDU_SECRET_KEY=DVTjYEKvImNmOpNNND9GOlQ0BIvzutGJ
      - BAIDU_DEV_PID=1537
      - AUTH_SECRET=my-secret-key-2024
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://backend:4001
    depends_on:
      - backend
    restart: always
